version: "3.7"
services:
  backup:
    image: frappe/erpnext:${FRAPPE_VERSION}
    entrypoint: ["bash", "-c"]
    command: |
      bench --site all backup
      ## Для restic-резервных копий:
      # restic snapshots || restic init
      # restic backup sites
      ## Хранить только последние 30 снимков:
      # restic forget --group-by=paths --keep-last=30 --prune
    environment:
      - RESTIC_REPOSITORY=${RESTIC_REPOSITORY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - RESTIC_PASSWORD=${RESTIC_PASSWORD}
    volumes:
      - "sites:/home/frappe/frappe-bench/sites"
    networks:
      - erpnext-network

networks:
  erpnext-network:
    external: true
    name: ${PROJECT_NAME:-erpnext}_default

volumes:
  sites:
    external: true
    name: ${PROJECT_NAME:-erpnext}_sites
