version: "3.7"
services:
  mariadb:
    image: docker.io/mariadb:10.6
    platform: linux/amd64
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed # Temporary fix for MariaDB 10.6
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mariadb-data:/var/lib/mysql

  redis-cache:
    image: docker.io/redis:alpine
    platform: linux/amd64
    command: redis-server --appendonly no --requirepass ${REDIS_CACHE_PASSWORD}

  redis-queue:
    image: docker.io/redis:alpine
    platform: linux/amd64
    command: redis-server --appendonly no --requirepass ${REDIS_QUEUE_PASSWORD}

  frappe:
    image: ferum_customs:version-15 # Custom image built from Dockerfile
    platform: linux/amd64
    env_file: .env
    environment:
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      REDIS_CACHE_HOST: redis-cache
      REDIS_CACHE_PORT: 6379
      REDIS_CACHE_PASSWORD: ${REDIS_CACHE_PASSWORD}
      REDIS_QUEUE_HOST: redis-queue
      REDIS_QUEUE_PORT: 6379
      REDIS_QUEUE_PASSWORD: ${REDIS_QUEUE_PASSWORD}
      SITE_NAME: ${SITE_NAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    volumes:
      - bench-vol:/home/frappe/frappe-bench
      - ./ferum_custom:/home/frappe/frappe-bench/apps/ferum_custom # Mount custom app for development
    working_dir: /home/frappe/frappe-bench
    ports:
      - "8000:8000"
    depends_on:
      - mariadb
      - redis-cache
      - redis-queue
    command: >
      bash -lc "
      # Create site if it doesn't exist
      if ! bench --site ${SITE_NAME} whoami >/dev/null 2>&1; then
        echo \"[frappe] Creating site ${SITE_NAME}...\"
        bench new-site ${SITE_NAME} \
          --db-type mariadb \
          --db-host mariadb \
          --db-name ${DB_NAME} \
          --db-user ${DB_USER} \
          --db-password ${DB_PASSWORD} \
          --admin-password ${ADMIN_PASSWORD} \
          --no-mariadb-socket
      else
        echo \"[frappe] Site ${SITE_NAME} already exists.\"
      fi

      # Install app on site if not already installed
      if ! bench --site ${SITE_NAME} list-apps | grep -q \"^ferum_customs$\"; then
        echo \"[frappe] Installing app on site...\"
        bench --site ${SITE_NAME} install-app ferum_customs
      else
        echo \"[frappe] App already installed on ${SITE_NAME}.\"
      fi

      # Run migrations
      bench --site ${SITE_NAME} migrate

      # Start bench
      bench start
      "

volumes:
  mariadb-data:
  bench-vol:
